Name:           perl-PAGI
Version:        0.001011
Release:        2%{?dist}
Summary:        Perl Asynchronous Gateway Interface
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/PAGI/
Source0:        http://www.cpan.org/modules/by-module/PAGI/PAGI-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
Conflicts:      perl-PAGI-Server < 0.001011
Obsoletes:      perl-PAGI-Server < 0.001011
BuildRequires:  perl >= 0:5.018
BuildRequires:  perl(Cookie::Baker) >= 0.11
BuildRequires:  perl(Cpanel::JSON::XS) >= 4.19
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Future) >= 0.50
BuildRequires:  perl(Future::AsyncAwait) >= 0.66
BuildRequires:  perl(HTTP::MultiPartParser) >= 0.02
BuildRequires:  perl(HTTP::Parser::XS) >= 0.17
BuildRequires:  perl(Hash::MultiValue) >= 0.16
BuildRequires:  perl(IO::Async) >= 0.802
BuildRequires:  perl(IO::Async::SSL) >= 0.25
BuildRequires:  perl(IO::Socket::IP)
BuildRequires:  perl(IO::Socket::SSL) >= 2.074
BuildRequires:  perl(JSON::MaybeXS) >= 1.004003
BuildRequires:  perl(Net::Async::HTTP) >= 0.49
BuildRequires:  perl(Net::Async::WebSocket::Client) >= 0.14
BuildRequires:  perl(Protocol::WebSocket) >= 0.26
BuildRequires:  perl(Sys::Sendfile) >= 0.11
BuildRequires:  perl(Test2::V0) >= 0.000159
BuildRequires:  perl(Test::Future::IO::Impl) >= 0.14
BuildRequires:  perl(Time::HiRes) >= 1.9764
BuildRequires:  perl(URI) >= 1.60
BuildRequires:  perl(URI::Escape) >= 5.09
Requires:       perl(Cookie::Baker) >= 0.11
Requires:       perl(Cpanel::JSON::XS) >= 4.19
Requires:       perl(Future) >= 0.50
Requires:       perl(Future::AsyncAwait) >= 0.66
Requires:       perl(HTTP::MultiPartParser) >= 0.02
Requires:       perl(HTTP::Parser::XS) >= 0.17
Requires:       perl(Hash::MultiValue) >= 0.16
Requires:       perl(IO::Async) >= 0.802
Requires:       perl(IO::Async::SSL) >= 0.25
Requires:       perl(IO::Socket::IP)
Requires:       perl(IO::Socket::SSL) >= 2.074
Requires:       perl(JSON::MaybeXS) >= 1.004003
Requires:       perl(Protocol::WebSocket) >= 0.26
Requires:       perl(Sys::Sendfile) >= 0.11
Requires:       perl(URI::Escape) >= 5.09
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
PAGI (Perl Asynchronous Gateway Interface) is a specification for
asynchronous Perl web applications, designed as a spiritual successor to
PSGI. It defines a standard interface between async-capable Perl web
servers, frameworks, and applications, supporting HTTP/1.1, WebSocket, and
Server-Sent Events (SSE).

%prep
%setup -q -n PAGI-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*
%{_bindir}/*

%changelog
* Fri Dec 26 2025 Michael R. Davis <mrdvt92@yahoo.com> 0.001008-1
- Specfile autogenerated by cpanspec 1.78.
